name:  Run Authentication Tests

on: [pull_request, push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run authentication tests
        run: pytest tests/
        shell: bash
