name: Run Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: git fetch origin main --depth 1
        shell: bash

      - name: Get Python Version
        id: get-python-version
        run: echo "VERSION=$(cat .python-version)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.get-python-version.outputs.VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Install hooks
        run: pre-commit install --install-hooks
        shell: bash

      - name: Run pre-commit hooks
        run: pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash

      # - name: Run Unit Tests
      #   run: ./bin/run_unit_tests.sh
      #   shell: bash
