---
name: Refresh Users Daily Quota

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    pull_request:
    branches:
      - "*"

jobs:
  refresh-quota:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get-python-version
        run: echo "VERSION=$(cat .python-version)" >> $GITHUB_ENV
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Refresh Users Daily Quota
        run: python3 ./bin/refresh_users_quota.py
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }},
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }},
          AWS_REGION: ${{ secrets.AWS_REGION }}
