name: Run Daily Scraper

on:
  schedule:
    # Runs every day at 0:00
    - cron: '23 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Do we need a more specific version??

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python ../Scaper/scraper_script.py
